INSERT INTO `card` (`deck`, `type`, `text`)
VALUES
    ('LIMITE_LIMITE', 'BLACK', 'Pendant que les français légalisaient le mariage gay, les belges légalisaient ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Quand je suis saoul, j\'ai tendance à confondre ▁▁▁▁▁▁▁ et ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Comment devenir riche en 2 étapes ?\n1: ▁▁▁▁▁▁▁\n2: ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Dans son prochain film, James Bond affrontera ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁ provoque le cancer'),
    ('LIMITE_LIMITE', 'BLACK', 'Si ▁▁▁▁▁▁▁ n\'existait pas, je serais encore vierge'),
    ('LIMITE_LIMITE', 'BLACK', 'J\'ai demandé ▁▁▁▁▁▁▁ au Père Noël mais j\'ai eu ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁, l\'ami du petit-déjeuner'),
    ('LIMITE_LIMITE', 'BLACK', 'L\'Egypte a les pyramides, la France a ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Ma copine m\'a avoué qu\'elle kiffait ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Quand je me sens triste je pense à ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁ est la seule raison pour laquelle je ne me suis toujours pas suicidé'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁, l\'astuce des couples qui durent'),
    ('LIMITE_LIMITE', 'BLACK', 'Le moyen de contraception le plus efficace reste quand même ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Seul remède contre le Sida: ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Judas décida de trahir Jésus quand il découvrit sa passion pour ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Pour résoudre les problèmes causés par ▁▁▁▁▁▁▁, Emmanuel Macron a dû faire appel à ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Quand j\'étais petit, les autres enfants rêvaient de devenir pompier, moi ce qui me faisait rêver c\'était ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Nicolas Sarkozy: « ▁▁▁▁▁▁▁ ? Je vais vous en débarasser au Kärcher »'),
    ('LIMITE_LIMITE', 'BLACK', 'Après 20 ans de débats, le Sénat a enfin voté l\'interdiction de ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'L\'unique faiblesse de Chuck Norris est ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Mon Dieu, merci pour ▁▁▁▁▁▁▁.\nAmen'),
    ('LIMITE_LIMITE', 'BLACK', 'Avertissement: ▁▁▁▁▁▁▁ provoque ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁, le cadeau parfait pour une femme qui a déjà tout'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁, à 5 ans tu en as peur, à 18 ans tu en raffoles'),
    ('LIMITE_LIMITE', 'BLACK', 'Les Rois Mages offrirent à Jésus en présent de l\'or, de l\'encens et ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'J\'espère que ma grand-mère ne me demandera jamais ce que ▁▁▁▁▁▁▁ signifie'),
    ('LIMITE_LIMITE', 'BLACK', 'Emmanuel Macron a quitté Brigitte pour une histoire de ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'National Geographic prévoit son prochain documentaire animalier sur ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Les qataris ont investi 30 milliards d\'euros pour éradiquer ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Il n\'y a rien de meilleur que ▁▁▁▁▁▁▁ avec ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Je n\'ai jamais vraiment compris ▁▁▁▁▁▁▁ jusqu\'a ce que je rencontre ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Si je me drogue autant, c\'est pour oublier ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Un ▁▁▁▁▁▁▁ vaut mieux que deux ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁: le fantasme qui fait mouiller 100% des bonnes soeurs'),
    ('LIMITE_LIMITE', 'BLACK', 'Le septième jour, Dieu créa ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Dans son dernier spectacle, Dieudonné compare ▁▁▁▁▁▁▁ avec ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Quand y\'en a marre, y\'a ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁, quand y\'en a un ça va, c\'est quand il y en a beaucoup qu\'il y a des problèmes'),
    ('LIMITE_LIMITE', 'BLACK', 'Si tu combines ▁▁▁▁▁▁▁ avec ▁▁▁▁▁▁▁ tu obtiens ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Demande à ton médecin si ▁▁▁▁▁▁▁ est bon pour toi'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁ me donne vraiment la gerbe'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁, c\'est encore meilleur la 2e fois'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁, ça fond dans la bouche, pas dans la main'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁ pour les nuls: le livre idéal pour la fête des mères'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁ ça a l\'air marrant mais en fait ça fait mal'),
    ('LIMITE_LIMITE', 'BLACK', 'Scandale à Clermont-Ferrant, un instituteur aurait montré ▁▁▁▁▁▁▁ à ses élèves'),
    ('LIMITE_LIMITE', 'BLACK', 'Quand je serai à la retraite, je créerai une association pour défendre ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Pour éviter l\'éjaculation précoce, je pense souvent à ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁, bon de la première cuillère jusqu\'à la dernière goutte'),
    ('LIMITE_LIMITE', 'BLACK', 'Ma dernière recherche Google: ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Les émeutes des gilets jaunes ont démarré quand Macron a voulu taxer ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'C\'est quoi cette bosse sous ton pantalon ? ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Rien ne remplacera jamais mon vibro, sauf ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Après une dure semaine de travail, j\'ai besoin de ▁▁▁▁▁▁▁ pour décompresser'),
    ('LIMITE_LIMITE', 'BLACK', 'Pourquoi je suis célibataire ? ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Et toi, qu\'est-ce que tu viens faire sur Tinder ? ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'La recherche la plus populaire sur Pornhub cette semaine ▁▁▁▁▁▁▁ + ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '- C\'est quoi ce bracelet électronique à ta cheville ?\n- Une sombre histoire de ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁, c\'est bio, vegan et sans gluten'),
    ('LIMITE_LIMITE', 'BLACK', '- Maman je n\'arrive pas à dormir, j\'ai trop peur de ▁▁▁▁▁▁▁\n- Ne t\'inquiète pas mon chéri, ce n\'est qu\'une légende'),
    ('LIMITE_LIMITE', 'BLACK', 'Selon l\'Evangile, Jésus peut tout pardonner sauf ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Bonjour à tous, voici mon nouveau mail: ▁▁▁▁▁▁▁@▁▁▁▁▁▁▁.com'),
    ('LIMITE_LIMITE', 'BLACK', 'Je n\'avais plus de capotes, j\'ai dû utiliser ▁▁▁▁▁▁▁ à la place'),
    ('LIMITE_LIMITE', 'BLACK', 'Quoi qu\'il arrive, ne mélange JAMAIS ▁▁▁▁▁▁▁ et ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Quand je perdais une dent, quel plaisir de découvrir le cadeau de la petite souris sous mon oreiller: ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', '▁▁▁▁▁▁▁ c\'est normal ? C\'est pour un pote'),
    ('LIMITE_LIMITE', 'BLACK', 'Selon nos statistiques, si vous aimez ▁▁▁▁▁▁▁ vous aimerez aussi ▁▁▁▁▁▁▁'),
    ('LIMITE_LIMITE', 'BLACK', 'Cher Papa, chère Maman, la colo se passe super bien. Hier mon copain Dylan nous a appris à ▁▁▁▁▁▁▁'),
    -- RED CARDS
    ('LIMITE_LIMITE', 'RED', 'L\'anus de Lara Croft'),
    ('LIMITE_LIMITE', 'RED', 'L\'OM'),
    ('LIMITE_LIMITE', 'RED', 'La mort du respect'),
    ('LIMITE_LIMITE', 'RED', 'Une tournante mal organisée'),
    ('LIMITE_LIMITE', 'RED', 'Une piscine remplie de caca'),
    ('LIMITE_LIMITE', 'RED', 'Un bébé raciste'),
    ('LIMITE_LIMITE', 'RED', 'Avoir la gaule en maillot de bain'),
    ('LIMITE_LIMITE', 'RED', 'La police du sexe anal'),
    ('LIMITE_LIMITE', 'RED', 'La contraception par la sodomie'),
    ('LIMITE_LIMITE', 'RED', 'Dire « Je t\'aime » à son plan cul'),
    ('LIMITE_LIMITE', 'RED', 'Une calvitie pubienne'),
    ('LIMITE_LIMITE', 'RED', 'Quatre vieux assis sur un tabouret à l\'envers'),
    ('LIMITE_LIMITE', 'RED', 'Un prêtre pédophile'),
    ('LIMITE_LIMITE', 'RED', 'Un mojito au GHB'),
    ('LIMITE_LIMITE', 'RED', 'Une partouze entre robots'),
    ('LIMITE_LIMITE', 'RED', 'Une kippah en solde chez H&M'),
    ('LIMITE_LIMITE', 'RED', 'Les filles qui mettent les dents'),
    ('LIMITE_LIMITE', 'RED', 'Des lasagnes Findus au cheval'),
    ('LIMITE_LIMITE', 'RED', 'Conserver ses excréments au congélateur'),
    ('LIMITE_LIMITE', 'RED', 'Une perfusion de cyprine'),
    ('LIMITE_LIMITE', 'RED', 'Les érections matinales incontrôlables'),
    ('LIMITE_LIMITE', 'RED', 'Les championnats du monde de pets vaginaux'),
    ('LIMITE_LIMITE', 'RED', 'Légaliser la pédophilie'),
    ('LIMITE_LIMITE', 'RED', 'Le suicide par crucificion'),
    ('LIMITE_LIMITE', 'RED', 'Le CAP dealer de drogue de Bobigny'),
    ('LIMITE_LIMITE', 'RED', 'La main droite de Jamel'),
    ('LIMITE_LIMITE', 'RED', 'Les vieilles filles qui dorment avec leur chat'),
    ('LIMITE_LIMITE', 'RED', 'Les grosses'),
    ('LIMITE_LIMITE', 'RED', 'La paix dans le monde'),
    ('LIMITE_LIMITE', 'RED', 'Ben Laden'),
    ('LIMITE_LIMITE', 'RED', 'Les prostituées chinoises'),
    ('LIMITE_LIMITE', 'RED', 'Les juifs imberbes'),
    ('LIMITE_LIMITE', 'RED', 'Les filles qui n\'avalent pas'),
    ('LIMITE_LIMITE', 'RED', 'Les écologistes qui roulent en 4x4'),
    ('LIMITE_LIMITE', 'RED', 'Les blancs qui écoutent du rap'),
    ('LIMITE_LIMITE', 'RED', 'L\'éducation sexuelle par l\'inceste'),
    ('LIMITE_LIMITE', 'RED', 'Le rétablissement de la peine de mort'),
    ('LIMITE_LIMITE', 'RED', 'La circoncision au cutter'),
    ('LIMITE_LIMITE', 'RED', 'Un obèse acnéique'),
    ('LIMITE_LIMITE', 'RED', 'Des traces de pneu'),
    ('LIMITE_LIMITE', 'RED', 'L\'alcoolisme infantile'),
    ('LIMITE_LIMITE', 'RED', 'La lingerie pour « femme rondes »'),
    ('LIMITE_LIMITE', 'RED', 'Les trisomiques'),
    ('LIMITE_LIMITE', 'RED', 'Les nazis'),
    ('LIMITE_LIMITE', 'RED', 'Les homosexuels refoulés'),
    ('LIMITE_LIMITE', 'RED', 'Les femmes fontaines'),
    ('LIMITE_LIMITE', 'RED', 'Les désespérés sur les sites de rencontre'),
    ('LIMITE_LIMITE', 'RED', 'Déféquer dans le bassin des bébés nageurs'),
    ('LIMITE_LIMITE', 'RED', 'Clara Morgane'),
    ('LIMITE_LIMITE', 'RED', 'Une diarrhée sanglante'),
    ('LIMITE_LIMITE', 'RED', 'Les blacks qui n\'aiment pas le KFC'),
    ('LIMITE_LIMITE', 'RED', 'L\'édition bibliothèque rose de Mein Kampf'),
    ('LIMITE_LIMITE', 'RED', 'L\'homophobie'),
    ('LIMITE_LIMITE', 'RED', 'L\'abolition du droit de vote des femmes'),
    ('LIMITE_LIMITE', 'RED', 'La formule all-you-can-fuck au bordel'),
    ('LIMITE_LIMITE', 'RED', 'Les tétraplégiques'),
    ('LIMITE_LIMITE', 'RED', 'Les MILFS siliconées'),
    ('LIMITE_LIMITE', 'RED', 'François Hollande'),
    ('LIMITE_LIMITE', 'RED', 'Une levrette claquée'),
    ('LIMITE_LIMITE', 'RED', 'La catégorie « Fat » de YouPorn'),
    ('LIMITE_LIMITE', 'RED', 'Les hipsters d\'extrême droite'),
    ('LIMITE_LIMITE', 'RED', 'Les femmes en Burqa'),
    ('LIMITE_LIMITE', 'RED', 'Les asiatiques bien montés'),
    ('LIMITE_LIMITE', 'RED', 'Le traffic de roux'),
    ('LIMITE_LIMITE', 'RED', 'Le porno gay allemand'),
    ('LIMITE_LIMITE', 'RED', 'La verge de DSK'),
    ('LIMITE_LIMITE', 'RED', 'Uriner dans l\'aquarium du resto chinois'),
    ('LIMITE_LIMITE', 'RED', 'Avoir un miroir au dessus de son lit'),
    ('LIMITE_LIMITE', 'RED', 'Faire l\'hélicoptère devant sa belle-mère'),
    ('LIMITE_LIMITE', 'RED', 'Des testicules trop pleins'),
    ('LIMITE_LIMITE', 'RED', 'Une racaille en mini-skis à Courchevel'),
    ('LIMITE_LIMITE', 'RED', 'Une mamie nymphomane'),
    ('LIMITE_LIMITE', 'RED', 'Une fellation au Wasabi'),
    ('LIMITE_LIMITE', 'RED', 'Un vibromasseur modelé sur la bite de Passe-Partout'),
    ('LIMITE_LIMITE', 'RED', 'Un régime à base de caca'),
    ('LIMITE_LIMITE', 'RED', 'La famine en Afrique'),
    ('LIMITE_LIMITE', 'RED', 'Kevin et Jenifer, parents à 15 ans'),
    ('LIMITE_LIMITE', 'RED', 'Découvrir qu\'on est papa sur Facebook'),
    ('LIMITE_LIMITE', 'RED', 'Bachar Al Assad'),
    ('LIMITE_LIMITE', 'RED', 'L\'iPhone'),
    ('LIMITE_LIMITE', 'RED', 'Etre réincarné en papier toilette'),
    ('LIMITE_LIMITE', 'RED', 'Les cathos'),
    ('LIMITE_LIMITE', 'RED', 'La cocaïne spéciale nourisson'),
    ('LIMITE_LIMITE', 'RED', 'Abandonner son enfant handicapé'),
    ('LIMITE_LIMITE', 'RED', 'Une comptable en chemisette'),
    ('LIMITE_LIMITE', 'RED', 'La sextape de Kim Kardashian'),
    ('LIMITE_LIMITE', 'RED', 'L\'allergie au latex'),
    ('LIMITE_LIMITE', 'RED', 'Se faire blanchir l\'anus'),
    ('LIMITE_LIMITE', 'RED', 'Jean-Claude Van Damme'),
    ('LIMITE_LIMITE', 'RED', 'Hitler'),
    ('LIMITE_LIMITE', 'RED', 'Dieudonné'),
    ('LIMITE_LIMITE', 'RED', 'Des serviettes « règles abondantes »'),
    ('LIMITE_LIMITE', 'RED', 'Jacquie et Michel'),
    ('LIMITE_LIMITE', 'RED', 'Echanger son fils contre un iPad'),
    ('LIMITE_LIMITE', 'RED', 'Des nains sodomites'),
    ('LIMITE_LIMITE', 'RED', 'Un risotto d\'hémorroïdes'),
    ('LIMITE_LIMITE', 'RED', 'Les illétrer'),
    ('LIMITE_LIMITE', 'RED', 'Angela Merkel'),
    ('LIMITE_LIMITE', 'RED', 'Une érection interminable'),
    ('LIMITE_LIMITE', 'RED', 'Une buche de Noël à base de bébés congelés'),
    ('LIMITE_LIMITE', 'RED', 'Un obèse seul pour la Saint Valentin'),
    ('LIMITE_LIMITE', 'RED', 'Se faire enterrer vivant'),
    ('LIMITE_LIMITE', 'RED', 'Un porno japonais en réalité virtuelle'),
    ('LIMITE_LIMITE', 'RED', 'S\'enfoncer les baguettes du resto japonais'),
    ('LIMITE_LIMITE', 'RED', 'Un acteur porno nain'),
    ('LIMITE_LIMITE', 'RED', 'Un burrito au Viagra'),
    ('LIMITE_LIMITE', 'RED', 'Un kebab de chaton'),
    ('LIMITE_LIMITE', 'RED', 'Un changement de trou surprise'),
    ('LIMITE_LIMITE', 'RED', 'Un Bloody Mary à base de menstruations'),
    ('LIMITE_LIMITE', 'RED', 'Faire semblant d\'avoir joui'),
    ('LIMITE_LIMITE', 'RED', 'Un enfant autiste ressemblant à François Hollande'),
    ('LIMITE_LIMITE', 'RED', 'Un charter rempli de sans papier'),
    ('LIMITE_LIMITE', 'RED', 'Un concombre introduit dans un anus'),
    ('LIMITE_LIMITE', 'RED', 'Un club échangiste pour handicapés'),
    ('LIMITE_LIMITE', 'RED', 'Un Carambar au Viagra'),
    ('LIMITE_LIMITE', 'RED', 'Un biberon rempli de sperme'),
    ('LIMITE_LIMITE', 'RED', 'Tomber sur la sextape de ses parents'),
    ('LIMITE_LIMITE', 'RED', 'Se rompre le frein en se masturbant'),
    ('LIMITE_LIMITE', 'RED', 'Se faire amputer d\'une jambe pour échapper à la JAPD'),
    ('LIMITE_LIMITE', 'RED', 'Matcher une grosse sur Tinder'),
    ('LIMITE_LIMITE', 'RED', 'Un gangbang en Afghanistan'),
    ('LIMITE_LIMITE', 'RED', 'S\'épiler le pubis avec du gros scotch'),
    ('LIMITE_LIMITE', 'RED', 'Epouser sa soeur'),
    ('LIMITE_LIMITE', 'RED', 'Se réveiller nu dans le bois de Boulogne'),
    ('LIMITE_LIMITE', 'RED', 'Rocco Siffredi'),
    ('LIMITE_LIMITE', 'RED', 'Sentir avant de lécher'),
    ('LIMITE_LIMITE', 'RED', 'Surprendre papi et mamie en levrette'),
    ('LIMITE_LIMITE', 'RED', 'Mettre une minijupe dans le RER B'),
    ('LIMITE_LIMITE', 'RED', 'Limoges, nouvelle plaque tournante du trafic de drogue'),
    ('LIMITE_LIMITE', 'RED', 'Faire semblant d\'être aveugle pour mater des culs'),
    ('LIMITE_LIMITE', 'RED', 'La poutre de Bamako'),
    ('LIMITE_LIMITE', 'RED', 'Un jacuzzi d\'urine'),
    ('LIMITE_LIMITE', 'RED', 'Un minibus d\'enfants leucémiques'),
    ('LIMITE_LIMITE', 'RED', 'Un chat bodybuildé'),
    ('LIMITE_LIMITE', 'RED', 'Un concours de mini-miss'),
    ('LIMITE_LIMITE', 'RED', 'Les lépreux'),
    ('LIMITE_LIMITE', 'RED', 'Un pet sanguinolent'),
    ('LIMITE_LIMITE', 'RED', 'Les roux beaux-gosses'),
    ('LIMITE_LIMITE', 'RED', 'Un singe qui baise une noix de coco'),
    ('LIMITE_LIMITE', 'RED', 'Les filles qui n\'aiment pas la sodomie'),
    ('LIMITE_LIMITE', 'RED', 'Le cancer colorectal'),
    ('LIMITE_LIMITE', 'RED', 'Une masturbation sur Gulli'),
    ('LIMITE_LIMITE', 'RED', 'Chuck Norris'),
    ('LIMITE_LIMITE', 'RED', 'Un milk-shake vanille / pilule du lendemain'),
    ('LIMITE_LIMITE', 'RED', 'La troisième jambe d\'Omar Sy'),
    ('LIMITE_LIMITE', 'RED', 'Eric Zemmour'),
    ('LIMITE_LIMITE', 'RED', 'Faire du vélo sans selle'),
    ('LIMITE_LIMITE', 'RED', 'Les féministes aux grosses cuisses'),
    ('LIMITE_LIMITE', 'RED', 'Les ch\'tis'),
    ('LIMITE_LIMITE', 'RED', 'Les marseillais'),
    ('LIMITE_LIMITE', 'RED', 'Se masturber dans le lit de ses parents'),
    ('LIMITE_LIMITE', 'RED', 'Une demi-molle'),
    ('LIMITE_LIMITE', 'RED', 'Le réparateur de photocopieuses des films X'),
    ('LIMITE_LIMITE', 'RED', 'Prostituer sa mamie'),
    ('LIMITE_LIMITE', 'RED', 'Mussolini'),
    ('LIMITE_LIMITE', 'RED', 'Un jerricane de lubrifiant'),
    ('LIMITE_LIMITE', 'RED', 'Transpirer abondamment de l\'anus'),
    ('LIMITE_LIMITE', 'RED', 'Le traditionnel bukakke du dimanche matin'),
    ('LIMITE_LIMITE', 'RED', 'Un bras d\'enfant'),
    ('LIMITE_LIMITE', 'RED', 'La triple pénétration'),
    ('LIMITE_LIMITE', 'RED', 'Acheter sa robe de mariée chez Tati'),
    ('LIMITE_LIMITE', 'RED', 'Avoir du sable dans l\'anus'),
    ('LIMITE_LIMITE', 'RED', 'Dans ton cul'),
    ('LIMITE_LIMITE', 'RED', 'Les renois'),
    ('LIMITE_LIMITE', 'RED', 'Se finir dans un chausson aux pommes'),
    ('LIMITE_LIMITE', 'RED', 'Un creampie'),
    ('LIMITE_LIMITE', 'RED', 'L\'haleine du prof de maths'),
    ('LIMITE_LIMITE', 'RED', 'Les juifs qui mangent du porc'),
    ('LIMITE_LIMITE', 'RED', 'Les vieux victimes de la canicule'),
    ('LIMITE_LIMITE', 'RED', 'Fêter ses 30 ans au McDo'),
    ('LIMITE_LIMITE', 'RED', 'Un défilé de mode en Arabie Saoudite'),
    ('LIMITE_LIMITE', 'RED', 'Les babtous fragiles'),
    ('LIMITE_LIMITE', 'RED', 'Une sodomie non consentie'),
    ('LIMITE_LIMITE', 'RED', 'Ma bite'),
    ('LIMITE_LIMITE', 'RED', 'Prendre conscience de son hétérosexualité lors de sa première expérience gay'),
    ('LIMITE_LIMITE', 'RED', 'La cicatrice de Ribéry'),
    ('LIMITE_LIMITE', 'RED', 'Un bijou d\'anus'),
    ('LIMITE_LIMITE', 'RED', 'Marc Dutroux'),
    ('LIMITE_LIMITE', 'RED', 'Les sans-dents'),
    ('LIMITE_LIMITE', 'RED', 'Un maçon portugais'),
    ('LIMITE_LIMITE', 'RED', 'Les mecs qui jouent à Limite Limite'),
    ('LIMITE_LIMITE', 'RED', 'La gérontophilie'),
    ('LIMITE_LIMITE', 'RED', 'La Fédération Française de Fist-Fucking (FFFF)'),
    ('LIMITE_LIMITE', 'RED', 'Une licorne avec une bite à la place de la corne'),
    ('LIMITE_LIMITE', 'RED', 'Un crématorium mal chauffé'),
    ('LIMITE_LIMITE', 'RED', 'Un clochard qui se masturbe en public'),
    ('LIMITE_LIMITE', 'RED', 'Les Roms'),
    ('LIMITE_LIMITE', 'RED', 'Trouver son enfant moche'),
    ('LIMITE_LIMITE', 'RED', 'Ta mère'),
    ('LIMITE_LIMITE', 'RED', 'Les corses'),
    ('LIMITE_LIMITE', 'RED', 'Un bébé sumo'),
    ('LIMITE_LIMITE', 'RED', 'Sucer après la sodomie'),
    ('LIMITE_LIMITE', 'RED', 'Oublier son bébé dans la voiture en plein mois d\'août'),
    ('LIMITE_LIMITE', 'RED', 'Militer pour l\'excision'),
    ('LIMITE_LIMITE', 'RED', 'L\'odeur des roux'),
    ('LIMITE_LIMITE', 'RED', 'Un enfant violé par Michael Jackson'),
    ('LIMITE_LIMITE', 'RED', 'Un cocktail à base de cyprine'),
    ('LIMITE_LIMITE', 'RED', 'Un piercing Barbie sur le clito'),
    ('LIMITE_LIMITE', 'RED', 'Sucer un tétraplégique'),
    ('LIMITE_LIMITE', 'RED', 'Une soirée jeu de la biscotte entre cousins'),
    ('LIMITE_LIMITE', 'RED', 'Un terroriste en moule bite'),
    ('LIMITE_LIMITE', 'RED', 'Un prépuce boursouflé'),
    ('LIMITE_LIMITE', 'RED', 'Un obèse qui n\'arrive pas à voir sa bite'),
    ('LIMITE_LIMITE', 'RED', 'Jean-Marie Le Pen'),
    ('LIMITE_LIMITE', 'RED', 'Vladimir Poutine'),
    ('LIMITE_LIMITE', 'RED', 'Une MST fatale'),
    ('LIMITE_LIMITE', 'RED', 'Une greffe de pénis'),
    ('LIMITE_LIMITE', 'RED', 'Une éjaculation dorsale'),
    ('LIMITE_LIMITE', 'RED', 'Une après-midi toucher rectal au CM2'),
    ('LIMITE_LIMITE', 'RED', 'Un tampax usagé'),
    ('LIMITE_LIMITE', 'RED', 'Un petit-déjeuner au picon bière'),
    ('LIMITE_LIMITE', 'RED', 'Un menu D3 à base de chien'),
    ('LIMITE_LIMITE', 'RED', 'La teub crochue de Cristiano Ronaldo'),
    ('LIMITE_LIMITE', 'RED', 'Une seringue infectée par le Sida'),
    ('LIMITE_LIMITE', 'RED', 'Acheter des petites culottes d\'occasion sur internet'),
    ('LIMITE_LIMITE', 'RED', 'Une fissure anale'),
    ('LIMITE_LIMITE', 'RED', 'Une colonie de vacances à Tchernobyl'),
    ('LIMITE_LIMITE', 'RED', 'Un cocktail Molotov à base de cyprine'),
    ('LIMITE_LIMITE', 'RED', 'Les gilets jaunes'),
    ('LIMITE_LIMITE', 'RED', 'Alexandre Benalla'),
    ('LIMITE_LIMITE', 'RED', 'Donald Trump'),
    ('LIMITE_LIMITE', 'RED', 'Se masturber dans un aspirateur'),
    ('LIMITE_LIMITE', 'RED', 'Passer son réveillon de Noël devant Arthur sur TF1'),
    ('LIMITE_LIMITE', 'RED', 'Violer un dauphin'),
    ('LIMITE_LIMITE', 'RED', 'Marine Le Pen Présidente de la République'),
    ('LIMITE_LIMITE', 'RED', 'Maître Gims'),
    ('LIMITE_LIMITE', 'RED', 'Un membre de 32cm'),
    ('LIMITE_LIMITE', 'RED', 'Un pénis sans testicules'),
    ('LIMITE_LIMITE', 'RED', 'Un restaurant cannibale'),
    ('LIMITE_LIMITE', 'RED', 'Un week-end en famille à la Fistinière');
