INSERT INTO `card` (`deck`, `type`, `text`)
VALUES
    ('BLANC_MANGER_COCO', 'BLACK', 'Aujourd\'hui ▁▁▁▁▁▁▁, #VDM'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Rater la naissance de son fils pour ▁▁▁▁▁▁▁, à la rigueur, ça peut se comprendre'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Les belles histoires commencent toujours par ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ ça passe, ▁▁▁▁▁▁▁ ça encore aussi why not, mais ▁▁▁▁▁▁▁ là je dis trop'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Pour le service réclamations, tapez 1, pour ▁▁▁▁▁▁▁ tapez 2, sinon veuillez patienter'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Le seul truc qui m\'embête vraiment avec la mondialisation, c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Il y a deux manières de sauver la France de la faillite, une grande réforme fiscale et ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, un travail bâclé'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est comme pour tout, il y a la théorie, et la pratique'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est la faute à pas-de-chance'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, un mal pour un bien'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est comme une bonne guerre, ça forge la jeunesse'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, pour moi, c\'est une belle métaphore du quinquennat de François Hollande'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ ne tue pas mais ▁▁▁▁▁▁▁ si'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ : challenge accepted !'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Ce qui distingue l\'homme de l\'animal à mon sens, c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '200m² orienté plein sud, calme, haut standing, et le petit plus est à la cave : ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'A quelques encablures du centre historique et loin de la cohue touristique, suivez le sentier côtier 5 minutes et venez admirer ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Quand une réunion client s\'annonce mal, je ramène ▁▁▁▁▁▁▁, en général ça détend l\'atmosphère'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, quand je te vois faire, je me dis que c\'est un art'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Pour me détendre le dimanche en fin d\'après-midi, avant de reprendre le boulot rien de tel que ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ : gros effort, petit résultat ; alors que ▁▁▁▁▁▁▁ : petit effort, gros résultat'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Vous allez me traiter de petite nature, mais ▁▁▁▁▁▁▁ il y a un quart d\'heure ça m\'a coupé l\'appétit'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Un truc sympa, simple et romantique pour le soir de la Saint-Valentin, c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Pour réussir ▁▁▁▁▁▁▁ il te manque ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Avant que je lise son testament, la dernière intention de votre père a été que je vous montre ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '800 g de viande hachée, 3 jaunes d\'oeufs, des câpres, de la sauce worcester et ▁▁▁▁▁▁▁ : là on tient un bon tartare'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ : je m\'en souviens pas. J\'étais bourré'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Le premier soir je me suis donc endormi sur le sable à mille milles de toute terre habitée. J\'étais bien plus isolé qu\'un naufragé sur un radeau au milieu de l\'océan. Alors vous imaginez ma surprise, au lever du jour, quand une drôle de petite voix m\'a réveillé. Elle disait : "S\'il vous plaît... dessinez-moi ▁▁▁▁▁▁▁"'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Malheureusement, avec votre apport initial, tout ce que notre banque peut vous proposer aujourd\'hui c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'J\'aime le papier à bulles, l\'odeur de la colle et ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'J\'ai toujours donné des petits noms à mes sextoys, celui-là s\'appelle ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, je ne nie pas les faits, je dis juste qu\'ils sont exagérés'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Tiens Roger, tu nous remettras ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est tout le bonheur que je souhaite, ma fille'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Afin de pimenter notre vie de couple après 35 ans de mariage, nous pratiquons ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est comme les mauvaises herbes : il faut traiter le problème à la racine'),
    ('BLANC_MANGER_COCO', 'BLACK', 'L\'acupuncture n\'a pas marché, l\'hypnose et l\'homéopathie non plus, alors ils ont tenté ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, le film'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ ?? Avec ça, les videurs te laisseront jamais rentrer'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Si tu plaides coupable pour ▁▁▁▁▁▁▁, tu peux t\'en tirer avec ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Si t\'es pas chaud tant pis, n\'empêche que ▁▁▁▁▁▁▁ normalement ça ne se refuse pas'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Tu mets ▁▁▁▁▁▁▁, puis ▁▁▁▁▁▁▁, tu mélanges et abracadabra : ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Chez nous, ▁▁▁▁▁▁▁ se transmet de père en fils depuis des années'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Alors ce week-end ? Bah comme d\'hab : vendredi soir ▁▁▁▁▁▁▁, samedi ▁▁▁▁▁▁▁ et donc dimanche matin ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'C\'est pas ce que je voulais dire, ▁▁▁▁▁▁▁, ce sont des propos sortis de leur contexte'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Un tournevis, tu as ? Non. Alors passe-moi ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Si j\'habitais en Californie, la chose qui me manquerait le plus de France, c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est le premier truc à larguer dans une montgolfière qui perd de l\'altitude'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, ça c\'est tellement ton père'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ c\'est un concept... On pourrait essayer'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Un truc à faire une fois dans sa vie, c\'est ▁▁▁▁▁▁▁... Mais seulement une fois'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est le prix à payer pour la paix dans le monde'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Vous n\'avez pas, M. Mitterrand, le monopole de ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ : le rêve, \n▁▁▁▁▁▁▁ : la réalité'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Luc Besson se demande comment intégrer ▁▁▁▁▁▁▁ et ▁▁▁▁▁▁▁ à son adaptation de la vie de Saint-Paul'),
    ('BLANC_MANGER_COCO', 'BLACK', 'C\'est quoi déjà ton truc qui marche bien contre les maux de gorge ?'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Plus que le mariage, ce qui a scellé notre union c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'A Abidjan, pour 1 euro tu peux avoir ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Les premiers rayons de soleil, le pollen dans l\'air, l\'amour, ▁▁▁▁▁▁▁, le printemps quoi'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ : l\'essayer c\'est l\'adopter'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ : Bien.\n▁▁▁▁▁▁▁ : Pas bien'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Vous avez aimé ▁▁▁▁▁▁▁, vous aimez ▁▁▁▁▁▁▁, vous allez aimer ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Père Noël, pour Noël je voudrais ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, YOLO'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ un problème, ▁▁▁▁▁▁▁ la solution'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est un détail à l\'échelle de l\'humanité'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Sans ▁▁▁▁▁▁▁, la fête est moins folle'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ : le meilleur remède contre la gueule de bois'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Ce qui m\'a permis de résister toutes ces années en prison, c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, j\'y pense tous les matins en me rasant'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Homme 45 ans, célibataire, bonne situation, cherche ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Mon investissement au Secours Catholique ? Je fais pas ça pour l\'argent, je fais pas ça pour la gloire mais pour ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Notre devis comprend aussi la livraison à votre domicile, un an d\'assurance et ▁▁▁▁▁▁▁ pour le client fidèle que vous êtes.'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Afin d\'apaiser les tensions interconfessionnelles dans le pays, le pape a prononcé un discours intitulé ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'J\'ai commencé ▁▁▁▁▁▁▁ quand j\'avais 7 ans et demi, j\'aurais peut-être dû attendre mes 9 ans'),
    ('BLANC_MANGER_COCO', 'BLACK', '3 trucs qui remontent le moral et c\'est physiologique, c\'est le chocolat, le soleil et ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'J\'ai 45 minutes de métro le matin pour aller au boulot, ça me laisse du temps pour ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'C\'est quoi ton mot de passe ? ▁▁▁▁▁▁▁ tout attaché'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ fait indéniablement partie de la culture française'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Pour moi les années 90 c\'est avant tout ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'La fin justifie ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ poil au nez, ▁▁▁▁▁▁▁ poil au bras'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, La Mecque n\'était peut-être pas l\'endroit le plus indiqué, tu y avais pensé ?'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ et ▁▁▁▁▁▁▁... Ou comment allier l\'utile à l\'agréable'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Un apéro sans pastis, et pourquoi pas ▁▁▁▁▁▁▁ sans ▁▁▁▁▁▁▁ tant qu\'on y est ?'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Si on se penche sur les statistiques, ▁▁▁▁▁▁▁ et ▁▁▁▁▁▁▁ sont étroitement corrélés'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, ça aurait dû se jouer à pile ou face'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ a marqué à coup sûr le premier jour du reste de ma vie'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Comparer ▁▁▁▁▁▁▁ et ▁▁▁▁▁▁▁, ce n\'est rendre justice ni à l\'un ni à l\'autre'),
    ('BLANC_MANGER_COCO', 'BLACK', 'J\'ai une technique simple pour réveiller en douceur un nouveau-né : ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Amen, je vous le dis, celui qui croit en moi aura ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, ça n\'existe pas, c\'est des fables, des balivernes'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Entre ▁▁▁▁▁▁▁ et une vie de famille, il faut choisir !'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Bon vent ! Mais fais attention à toi, ▁▁▁▁▁▁▁ est si vite arrivé'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Le 8e jour, Dieu créa ▁▁▁▁▁▁▁ et il vit que cela était bon'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Papa, c\'est quoi ▁▁▁▁▁▁▁ ?'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est un luxe en période de crise'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, c\'est en quelque sorte ma madeleine de Proust'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, ça m\'a pris 2 minutes et encore je me suis pas pressé'),
    ('BLANC_MANGER_COCO', 'BLACK', 'En 3 je mets le travail, en 2 la famille et en 1 ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Oui mon enfant, Dieu pardonne tout, même ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁, mes beaux-parents dominent allègrement le classement, et de loin'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Il y aura une baby-sitter pour le mariage ? Non mais on a quand même prévu, on a ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Contre toute attente, Martine et ▁▁▁▁▁▁▁ a été l\'opus le moins vendu de la série'),
    ('BLANC_MANGER_COCO', 'BLACK', 'La gauche va pousser le thème du dialogue social, il faut absolument recentrer le débat sur ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Pour égayer la vie d\'un enfant aveugle, donne lui ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'On a d\'abord cru à un canular mais AQMI a bel et bien exigé ▁▁▁▁▁▁▁ pour la libération des 3 otages'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Tu préfères ▁▁▁▁▁▁▁ ou bien ▁▁▁▁▁▁▁ ?'),
    ('BLANC_MANGER_COCO', 'BLACK', '▁▁▁▁▁▁▁ c\'est bien, ▁▁▁▁▁▁▁ c\'est mieux'),
    ('BLANC_MANGER_COCO', 'BLACK', '"Pour Grand Maître Jedi devenir, ▁▁▁▁▁▁▁ tu feras"'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Petit on n\'avait besoin de rien, on pourait jouer une journée entière avec ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Quand j\'ai rencontré ta mère, ça a tout de suite été ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Promis, à partir du 1er Javier, j\'arrête ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Bon... ▁▁▁▁▁▁▁, on l\'a tous fait un jour ou l\'autre'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Le meilleur moyen aujourd\'hui pour lutter contre la surnatalité en Afrique, c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Une GoPro c\'est un peu gadget, mais c\'est vrai que pour ▁▁▁▁▁▁▁, ça peut se justifier'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Changer une vitre c\'est comme ▁▁▁▁▁▁▁ : tu le feras aussi bien tout seul et ça te coûteras moins cher'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Oui ! Avec le Pack Sérénité votre logement est même assuré contre ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Le péché mignon de Grand-Père, c\'est ▁▁▁▁▁▁▁, c\'est pour ça qu\'on le trouve tous trop cool'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Mon dernier post Facebook est un selfie de moi avec ▁▁▁▁▁▁▁, j\'ai eu 27 like'),
    ('BLANC_MANGER_COCO', 'BLACK', 'J\'ai peut-être pas d\'amis, pas de copine et pas de boulot, mais j\'ai ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Au fond, ce qui manquait le plus à Auschwitz, c\'était ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Jusqu\'à ce qu\'elle évoque ▁▁▁▁▁▁▁, on passait presque un bon moment avec ma belle-mère'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Le sujet de ma thèse de doctorat, ▁▁▁▁▁▁▁, a été étonnamment mal reçu par le jury'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Ca en a le goût, ça en a la texture la couleur, mais ce n\'est pas ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', '"Je suis Monsieur Marc, vous notez : M comme maison, A comme Arbre, R comme Romeo, C comme ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'C\'est quoi ton parfum ? ▁▁▁▁▁▁▁ de Guerlain'),
    ('BLANC_MANGER_COCO', 'BLACK', 'La vraie raison de mes premiers cheveux blancs, c\'est ▁▁▁▁▁▁▁'),
    ('BLANC_MANGER_COCO', 'BLACK', 'Petit SMS pour vous souhaiter beaucoup de bonheur et ▁▁▁▁▁▁▁ pour cette nouvelle année'),
    ('BLANC_MANGER_COCO', 'BLACK', 'A 75 ans, il y a 2 choses que tu regrettes : ▁▁▁▁▁▁▁ et surtout ▁▁▁▁▁▁▁');

INSERT INTO `card` (`deck`, `type`, `text`)
VALUES
    ('BLANC_MANGER_COCO', 'RED', 'Être gardien au handball'),
    ('BLANC_MANGER_COCO', 'RED', 'Le caca mou du lendemain de soirée'),
    ('BLANC_MANGER_COCO', 'RED', '1 kg d\'amiante'),
    ('BLANC_MANGER_COCO', 'RED', 'Les fautes de goût'),
    ('BLANC_MANGER_COCO', 'RED', 'Les envies de femme enceinte'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'intégrale de Katsuni'),
    ('BLANC_MANGER_COCO', 'RED', 'Les femmes qui font le poirier après l\'amour'),
    ('BLANC_MANGER_COCO', 'RED', 'Violer une chèvre'),
    ('BLANC_MANGER_COCO', 'RED', 'Refuser un test de paternité'),
    ('BLANC_MANGER_COCO', 'RED', 'Un oeil pour un oeil'),
    ('BLANC_MANGER_COCO', 'RED', 'La France'),
    ('BLANC_MANGER_COCO', 'RED', 'Les goudous'),
    ('BLANC_MANGER_COCO', 'RED', 'Le quinquennat de François Hollande'),
    ('BLANC_MANGER_COCO', 'RED', 'Une lapidation en bonne et due forme'),
    ('BLANC_MANGER_COCO', 'RED', 'Une place handicapé'),
    ('BLANC_MANGER_COCO', 'RED', 'Une pause gourmande'),
    ('BLANC_MANGER_COCO', 'RED', 'La gangrène généralisée'),
    ('BLANC_MANGER_COCO', 'RED', 'La droite décomplexée'),
    ('BLANC_MANGER_COCO', 'RED', 'Sortir du placard'),
    ('BLANC_MANGER_COCO', 'RED', 'Passer une soirée en boîte en note de frais'),
    ('BLANC_MANGER_COCO', 'RED', 'Marc Dutroux'),
    ('BLANC_MANGER_COCO', 'RED', 'Le bonnet rouge du commandant Cousteau'),
    ('BLANC_MANGER_COCO', 'RED', 'Une soutane et rien dessous'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'aide alimentaire pour la Somalie'),
    ('BLANC_MANGER_COCO', 'RED', 'Rédiger des scripts pour mendiants'),
    ('BLANC_MANGER_COCO', 'RED', 'Le sperme qui colle sur la baignoire'),
    ('BLANC_MANGER_COCO', 'RED', 'Les femmes'),
    ('BLANC_MANGER_COCO', 'RED', 'Secouer la petite gouette'),
    ('BLANC_MANGER_COCO', 'RED', 'Enculer les mouches'),
    ('BLANC_MANGER_COCO', 'RED', 'Relire Mein Kampf'),
    ('BLANC_MANGER_COCO', 'RED', 'Un PSG/OM avec des pizzas et des bières'),
    ('BLANC_MANGER_COCO', 'RED', 'Le best-of des chansons paillardes'),
    ('BLANC_MANGER_COCO', 'RED', 'Les femmes au volant'),
    ('BLANC_MANGER_COCO', 'RED', 'La paix dans le monde'),
    ('BLANC_MANGER_COCO', 'RED', 'Les bonnes manières'),
    ('BLANC_MANGER_COCO', 'RED', 'Bourrer les urnes'),
    ('BLANC_MANGER_COCO', 'RED', 'Un toucher rectal'),
    ('BLANC_MANGER_COCO', 'RED', 'Commencer avec le doigt, finir avec le bras'),
    ('BLANC_MANGER_COCO', 'RED', 'Chier et pisser en même temps'),
    ('BLANC_MANGER_COCO', 'RED', 'Le concile Vatican 3'),
    ('BLANC_MANGER_COCO', 'RED', 'Joseph Goebbels'),
    ('BLANC_MANGER_COCO', 'RED', 'Envoyer "Amour" au 8 200 200'),
    ('BLANC_MANGER_COCO', 'RED', 'Faire une croix sur les caresses et les préliminaires'),
    ('BLANC_MANGER_COCO', 'RED', 'Voler les caisses de Médecins Sans Frontières'),
    ('BLANC_MANGER_COCO', 'RED', 'S\'en foutre plein les fouilles'),
    ('BLANC_MANGER_COCO', 'RED', 'Marcher pieds nus dans une salle de shoot'),
    ('BLANC_MANGER_COCO', 'RED', 'Une petite pièce, une cigarette ou un ticket restaurant'),
    ('BLANC_MANGER_COCO', 'RED', 'Les fesses potelées'),
    ('BLANC_MANGER_COCO', 'RED', 'Une entorse au protocole'),
    ('BLANC_MANGER_COCO', 'RED', 'Un bébé contre le sein de sa mère'),
    ('BLANC_MANGER_COCO', 'RED', 'Le Journal du hard'),
    ('BLANC_MANGER_COCO', 'RED', 'Le caviar Beluga'),
    ('BLANC_MANGER_COCO', 'RED', 'Une étagère Billy'),
    ('BLANC_MANGER_COCO', 'RED', 'Dodo la Saumure'),
    ('BLANC_MANGER_COCO', 'RED', 'Vivel Dop Fixation Béton'),
    ('BLANC_MANGER_COCO', 'RED', 'Les maximes de La Rochefoucauld'),
    ('BLANC_MANGER_COCO', 'RED', 'Respecter les quotas'),
    ('BLANC_MANGER_COCO', 'RED', 'Work hard - Play hard'),
    ('BLANC_MANGER_COCO', 'RED', 'Le tic-tac de l\'horloge biologique'),
    ('BLANC_MANGER_COCO', 'RED', 'Un pet de fouffe'),
    ('BLANC_MANGER_COCO', 'RED', 'La consanguinité'),
    ('BLANC_MANGER_COCO', 'RED', 'Jacquie et Michel'),
    ('BLANC_MANGER_COCO', 'RED', 'Un poireau sur la joue'),
    ('BLANC_MANGER_COCO', 'RED', 'Le problème de l\'amiante dans le couloir de la mort'),
    ('BLANC_MANGER_COCO', 'RED', 'Traiter les femmes avec respect'),
    ('BLANC_MANGER_COCO', 'RED', 'Tirer une taffe après 6 mois sans clope'),
    ('BLANC_MANGER_COCO', 'RED', 'Un papillon tatoué dans le bas du dos'),
    ('BLANC_MANGER_COCO', 'RED', 'Charrier un videur'),
    ('BLANC_MANGER_COCO', 'RED', 'www.impots.gouv.fr'),
    ('BLANC_MANGER_COCO', 'RED', 'Saga Africa, ambiance de la brousse'),
    ('BLANC_MANGER_COCO', 'RED', 'Manger la couenne'),
    ('BLANC_MANGER_COCO', 'RED', 'Appeler un chat un chat'),
    ('BLANC_MANGER_COCO', 'RED', 'Un abonnement à Famille Chrétiennes'),
    ('BLANC_MANGER_COCO', 'RED', 'Péter sur le mec qui refuse de se lever de son strapontin'),
    ('BLANC_MANGER_COCO', 'RED', 'Un Français bien de chez nous'),
    ('BLANC_MANGER_COCO', 'RED', 'Perdre 1,2 kg quand on en pèse 123'),
    ('BLANC_MANGER_COCO', 'RED', 'Hiroshima'),
    ('BLANC_MANGER_COCO', 'RED', 'Un viol collectif'),
    ('BLANC_MANGER_COCO', 'RED', 'La pétanque'),
    ('BLANC_MANGER_COCO', 'RED', 'Une cuillère tordue, un briquet et une seringue'),
    ('BLANC_MANGER_COCO', 'RED', 'La gueule de bois'),
    ('BLANC_MANGER_COCO', 'RED', 'Une bonne grosse teuf'),
    ('BLANC_MANGER_COCO', 'RED', 'Coucher le premier soir'),
    ('BLANC_MANGER_COCO', 'RED', 'Soweto'),
    ('BLANC_MANGER_COCO', 'RED', 'Une pinte de glaire'),
    ('BLANC_MANGER_COCO', 'RED', 'Le verre de trop'),
    ('BLANC_MANGER_COCO', 'RED', 'Investir dans une particule'),
    ('BLANC_MANGER_COCO', 'RED', 'Patrick Sébastien'),
    ('BLANC_MANGER_COCO', 'RED', 'Les francs-maçons'),
    ('BLANC_MANGER_COCO', 'RED', 'La légitime défense'),
    ('BLANC_MANGER_COCO', 'RED', 'Des ladyboys séropositifs'),
    ('BLANC_MANGER_COCO', 'RED', 'La Manif Pour Tous'),
    ('BLANC_MANGER_COCO', 'RED', 'Le port du voile intégral'),
    ('BLANC_MANGER_COCO', 'RED', 'Le petit Grégory'),
    ('BLANC_MANGER_COCO', 'RED', 'Une raison de continuer à y croire'),
    ('BLANC_MANGER_COCO', 'RED', 'Lucy l\'Australopithèque'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'Amicale des Anciens Kmers Rouges'),
    ('BLANC_MANGER_COCO', 'RED', 'Un pet humide juste ce qu\'il faut'),
    ('BLANC_MANGER_COCO', 'RED', 'Apprendre qu\'on est cocu sur Closer'),
    ('BLANC_MANGER_COCO', 'RED', 'La levrette avec un chapeau de cowboy'),
    ('BLANC_MANGER_COCO', 'RED', 'Le subjonctif imparfait'),
    ('BLANC_MANGER_COCO', 'RED', 'Les rudiments de l\'hygiène corporelle'),
    ('BLANC_MANGER_COCO', 'RED', 'Marcher pieds nus sur un Lego'),
    ('BLANC_MANGER_COCO', 'RED', 'Avoir une bouteille de Pétrus et pas de tire-bouchon'),
    ('BLANC_MANGER_COCO', 'RED', 'Être VIP au Macumba'),
    ('BLANC_MANGER_COCO', 'RED', 'La traditionnelle gaule matinale'),
    ('BLANC_MANGER_COCO', 'RED', 'Un mâle reproducteur'),
    ('BLANC_MANGER_COCO', 'RED', 'Flamby'),
    ('BLANC_MANGER_COCO', 'RED', 'Trois doigts dans le cul'),
    ('BLANC_MANGER_COCO', 'RED', 'Guillaume Musso'),
    ('BLANC_MANGER_COCO', 'RED', 'Un cul pas plus large que ça'),
    ('BLANC_MANGER_COCO', 'RED', 'Je t\'aime, moi non plus'),
    ('BLANC_MANGER_COCO', 'RED', 'Chier vert'),
    ('BLANC_MANGER_COCO', 'RED', 'Serrer les fesses'),
    ('BLANC_MANGER_COCO', 'RED', 'Ejaculer après 47 secondes'),
    ('BLANC_MANGER_COCO', 'RED', 'Se curer le nez'),
    ('BLANC_MANGER_COCO', 'RED', 'Le coup de grâce'),
    ('BLANC_MANGER_COCO', 'RED', 'Faire un geste pour la planète'),
    ('BLANC_MANGER_COCO', 'RED', 'Ouvrir un compte en Suisse'),
    ('BLANC_MANGER_COCO', 'RED', 'La misère'),
    ('BLANC_MANGER_COCO', 'RED', 'Payer pour voir des films porno en 2016'),
    ('BLANC_MANGER_COCO', 'RED', 'Une banane pour Taubira'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'industrie de l\'armement'),
    ('BLANC_MANGER_COCO', 'RED', 'Le rétablissement de la peine de mort'),
    ('BLANC_MANGER_COCO', 'RED', 'Une épisiotomie sans péridurale'),
    ('BLANC_MANGER_COCO', 'RED', 'Les bancs'),
    ('BLANC_MANGER_COCO', 'RED', 'Les juifs'),
    ('BLANC_MANGER_COCO', 'RED', 'Une grossesse prématurée'),
    ('BLANC_MANGER_COCO', 'RED', 'La ligue des éjaculateur précoces'),
    ('BLANC_MANGER_COCO', 'RED', 'Un désaccord sur la notion de consentement'),
    ('BLANC_MANGER_COCO', 'RED', 'Une vie de petit bourgeois'),
    ('BLANC_MANGER_COCO', 'RED', 'Les noirs'),
    ('BLANC_MANGER_COCO', 'RED', 'Un dîner chez la belle famille'),
    ('BLANC_MANGER_COCO', 'RED', 'Prendre un enfant par la main'),
    ('BLANC_MANGER_COCO', 'RED', 'Enterrer une pute un désert'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'odeur du chemisier de Grand-Mère'),
    ('BLANC_MANGER_COCO', 'RED', 'Dachau'),
    ('BLANC_MANGER_COCO', 'RED', 'Le génocide arménien'),
    ('BLANC_MANGER_COCO', 'RED', 'Ta Maman'),
    ('BLANC_MANGER_COCO', 'RED', 'La pilule du lendemain'),
    ('BLANC_MANGER_COCO', 'RED', 'Une histoire d\'amour avec un curé de 62 ans'),
    ('BLANC_MANGER_COCO', 'RED', 'Le sexe punitif'),
    ('BLANC_MANGER_COCO', 'RED', 'Vladimir Poutine'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'euthanasie systématique à 75 ans'),
    ('BLANC_MANGER_COCO', 'RED', 'Ma chatte bien sûr !!'),
    ('BLANC_MANGER_COCO', 'RED', 'Jouir ou mourir'),
    ('BLANC_MANGER_COCO', 'RED', 'Les arabes'),
    ('BLANC_MANGER_COCO', 'RED', 'Du chocolat pour attirer les enfants'),
    ('BLANC_MANGER_COCO', 'RED', 'un ver solitaire'),
    ('BLANC_MANGER_COCO', 'RED', 'Acheter les alliances chez Tati or'),
    ('BLANC_MANGER_COCO', 'RED', 'Une bouteille de pastis et un Justin Bridou à partager'),
    ('BLANC_MANGER_COCO', 'RED', 'Une thèse sur les modèles prédictifs de la susceptibilité des cellules souches pluripotentes'),
    ('BLANC_MANGER_COCO', 'RED', 'Ta soeur qui est aussi ta mère'),
    ('BLANC_MANGER_COCO', 'RED', 'La sauce samouraï'),
    ('BLANC_MANGER_COCO', 'RED', 'Enfiler sa burka'),
    ('BLANC_MANGER_COCO', 'RED', 'Se triturer le gland'),
    ('BLANC_MANGER_COCO', 'RED', 'Les punks à chien'),
    ('BLANC_MANGER_COCO', 'RED', 'Prendre l\'hélico avec Balavoine et Florence Arthaud'),
    ('BLANC_MANGER_COCO', 'RED', 'Avaler l\'éthylotest'),
    ('BLANC_MANGER_COCO', 'RED', 'Licencier une mère célibataire'),
    ('BLANC_MANGER_COCO', 'RED', 'Une blague bien misogyne comme on les aime'),
    ('BLANC_MANGER_COCO', 'RED', 'Un couscous aux lardons'),
    ('BLANC_MANGER_COCO', 'RED', 'Une démocratie à l\'africaine'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'adoption par les couples zoophiles'),
    ('BLANC_MANGER_COCO', 'RED', 'Un bébé qui flotte dans un étang'),
    ('BLANC_MANGER_COCO', 'RED', 'Titiller la prostate'),
    ('BLANC_MANGER_COCO', 'RED', 'Battre sa femme'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'égalité homme-femme'),
    ('BLANC_MANGER_COCO', 'RED', 'Le passage du salaire brut au net'),
    ('BLANC_MANGER_COCO', 'RED', 'Ma bite'),
    ('BLANC_MANGER_COCO', 'RED', 'Les doigts qui collent'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'orgasme total'),
    ('BLANC_MANGER_COCO', 'RED', 'Dire "je t\'aime" sans vraiment le penser'),
    ('BLANC_MANGER_COCO', 'RED', 'La charia'),
    ('BLANC_MANGER_COCO', 'RED', 'Europe Écologie les Verts'),
    ('BLANC_MANGER_COCO', 'RED', 'Annexer la Wallonie'),
    ('BLANC_MANGER_COCO', 'RED', 'Marion Maréchal-Le Pen'),
    ('BLANC_MANGER_COCO', 'RED', 'Une orgie de frères bénédictions'),
    ('BLANC_MANGER_COCO', 'RED', 'Le cumul des mandats'),
    ('BLANC_MANGER_COCO', 'RED', 'Une crampe au poignet'),
    ('BLANC_MANGER_COCO', 'RED', 'Émile Louis'),
    ('BLANC_MANGER_COCO', 'RED', 'Céline Dion'),
    ('BLANC_MANGER_COCO', 'RED', 'Un magret de canard, Nutella, cornichons, mascarpone'),
    ('BLANC_MANGER_COCO', 'RED', 'Sortir l\'artillerie lourde'),
    ('BLANC_MANGER_COCO', 'RED', 'Les énarques'),
    ('BLANC_MANGER_COCO', 'RED', 'Kärcher à volonté'),
    ('BLANC_MANGER_COCO', 'RED', 'La Françafrique'),
    ('BLANC_MANGER_COCO', 'RED', 'Laisser 10 centimes de pourboire'),
    ('BLANC_MANGER_COCO', 'RED', '1 litre et demi de purin'),
    ('BLANC_MANGER_COCO', 'RED', 'La beauf attitude'),
    ('BLANC_MANGER_COCO', 'RED', 'Un coup de genou là où ça fait mal'),
    ('BLANC_MANGER_COCO', 'RED', 'Les filles de l\'Est'),
    ('BLANC_MANGER_COCO', 'RED', 'Louer un poney'),
    ('BLANC_MANGER_COCO', 'RED', 'Les caves de Sarcelles'),
    ('BLANC_MANGER_COCO', 'RED', 'Un Paki avec un bouquet de roses'),
    ('BLANC_MANGER_COCO', 'RED', 'Le Costa Concordia'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'acné juvénile'),
    ('BLANC_MANGER_COCO', 'RED', 'Mettre un aileron sur une Fiat Punto'),
    ('BLANC_MANGER_COCO', 'RED', 'Une maison avec jardin à Melun, une Opel Vectra et un labrador'),
    ('BLANC_MANGER_COCO', 'RED', 'En avoir plein le cul'),
    ('BLANC_MANGER_COCO', 'RED', 'se torcher avec la Convention de Genève'),
    ('BLANC_MANGER_COCO', 'RED', 'La mort du petit Aylan'),
    ('BLANC_MANGER_COCO', 'RED', 'La propension naturelle des femmes à s\'occuper des enfants et du foyer'),
    ('BLANC_MANGER_COCO', 'RED', 'Faire le une de FHM'),
    ('BLANC_MANGER_COCO', 'RED', 'Une chambre à l\'heure'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'inspection des travaux finis'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'amant de ma femme'),
    ('BLANC_MANGER_COCO', 'RED', '100 balles et 1 Mars'),
    ('BLANC_MANGER_COCO', 'RED', 'Le ceinture de chasteté'),
    ('BLANC_MANGER_COCO', 'RED', 'Une femme fontaine'),
    ('BLANC_MANGER_COCO', 'RED', 'La double pénétration'),
    ('BLANC_MANGER_COCO', 'RED', 'Une belle paire de nibards'),
    ('BLANC_MANGER_COCO', 'RED', 'Deux doigts dans le cul'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'esprit Daech'),
    ('BLANC_MANGER_COCO', 'RED', 'Les grands donateurs de la banque du sperme'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'acharnement thérapeutique'),
    ('BLANC_MANGER_COCO', 'RED', 'Les activités extra-conjugales'),
    ('BLANC_MANGER_COCO', 'RED', '21 cm de bonheur'),
    ('BLANC_MANGER_COCO', 'RED', 'La France de Vichy'),
    ('BLANC_MANGER_COCO', 'RED', 'Mettre un Bébé dans la cave'),
    ('BLANC_MANGER_COCO', 'RED', 'Proposer une clope à un dauphin'),
    ('BLANC_MANGER_COCO', 'RED', '100 ml de laxatif'),
    ('BLANC_MANGER_COCO', 'RED', 'Être en coloc avec Papa'),
    ('BLANC_MANGER_COCO', 'RED', 'Les problèmes de riches'),
    ('BLANC_MANGER_COCO', 'RED', 'Les prêtres pédophiles'),
    ('BLANC_MANGER_COCO', 'RED', 'Aménager un espace pour les roux'),
    ('BLANC_MANGER_COCO', 'RED', 'La conduite en état d\'ivresse'),
    ('BLANC_MANGER_COCO', 'RED', 'Un sandwich triangle sur une aire d\'autoroute'),
    ('BLANC_MANGER_COCO', 'RED', 'Le slip kangourou'),
    ('BLANC_MANGER_COCO', 'RED', '3 petits pschitts de Febreze'),
    ('BLANC_MANGER_COCO', 'RED', 'Un zizi-oreille au petit matin'),
    ('BLANC_MANGER_COCO', 'RED', 'Égorger le mouton dans la baignoire'),
    ('BLANC_MANGER_COCO', 'RED', 'La jurisprudence Nafissatou Diallo'),
    ('BLANC_MANGER_COCO', 'RED', 'La réunionite'),
    ('BLANC_MANGER_COCO', 'RED', '30 ans de gonzo'),
    ('BLANC_MANGER_COCO', 'RED', 'La Malaysia Airlines'),
    ('BLANC_MANGER_COCO', 'RED', 'Un frigo vide'),
    ('BLANC_MANGER_COCO', 'RED', 'Une plâtrée de choux de Bruxelles'),
    ('BLANC_MANGER_COCO', 'RED', 'Le grand théorème de Fermat'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'huile de foie de morue'),
    ('BLANC_MANGER_COCO', 'RED', 'Ségolène, Valérie et Julie'),
    ('BLANC_MANGER_COCO', 'RED', 'Faire l\'amour et garder ses chaussettes'),
    ('BLANC_MANGER_COCO', 'RED', 'Dépuceler sans ménagement ni tendresse'),
    ('BLANC_MANGER_COCO', 'RED', 'Parler la bouche pleine'),
    ('BLANC_MANGER_COCO', 'RED', 'Quitter Neuilly'),
    ('BLANC_MANGER_COCO', 'RED', 'La sourire honnête et franc de mon banquier'),
    ('BLANC_MANGER_COCO', 'RED', 'La grasse matinée'),
    ('BLANC_MANGER_COCO', 'RED', 'Le gars qui crie POPOPOPOPOPOPOPOLOLO à Roland-Garros'),
    ('BLANC_MANGER_COCO', 'RED', 'Des menottes et un leg-in en latex'),
    ('BLANC_MANGER_COCO', 'RED', 'Un Notre-Père et dix Je-vous-salue-Marie'),
    ('BLANC_MANGER_COCO', 'RED', 'Viser les pastilles de chlore bleues quand on pisse'),
    ('BLANC_MANGER_COCO', 'RED', 'Croire au Père Noël'),
    ('BLANC_MANGER_COCO', 'RED', 'Un canard en plastique jaune'),
    ('BLANC_MANGER_COCO', 'RED', 'Le colonel Moutarde dans la cuisine'),
    ('BLANC_MANGER_COCO', 'RED', 'Le Carlton de Lille'),
    ('BLANC_MANGER_COCO', 'RED', 'Un conflit multipolarisé d\'envergure internationale'),
    ('BLANC_MANGER_COCO', 'RED', 'Le droit de cuissage'),
    ('BLANC_MANGER_COCO', 'RED', '1 milliard d\'euros'),
    ('BLANC_MANGER_COCO', 'RED', 'Prendre le deuxième Big Mac à 1 euro'),
    ('BLANC_MANGER_COCO', 'RED', 'Le dernier jour du condamné'),
    ('BLANC_MANGER_COCO', 'RED', 'Un SMS qui dit qu\'on arrive dans 15 minutes alors que pas du tout'),
    ('BLANC_MANGER_COCO', 'RED', 'Prendre possession du podium'),
    ('BLANC_MANGER_COCO', 'RED', 'Faire une fausse promesse de don au Téléthon'),
    ('BLANC_MANGER_COCO', 'RED', 'La gastronomie allemande'),
    ('BLANC_MANGER_COCO', 'RED', 'Le vin en cubi'),
    ('BLANC_MANGER_COCO', 'RED', 'Un noir, une pute, un belge et un homo'),
    ('BLANC_MANGER_COCO', 'RED', 'Magic System'),
    ('BLANC_MANGER_COCO', 'RED', 'Un sauna gay'),
    ('BLANC_MANGER_COCO', 'RED', 'Un sorbet au foutre'),
    ('BLANC_MANGER_COCO', 'RED', 'Une piqûre de testostérone'),
    ('BLANC_MANGER_COCO', 'RED', 'Candy Crush'),
    ('BLANC_MANGER_COCO', 'RED', 'Trouver la fréquence des baby-phones du quartier'),
    ('BLANC_MANGER_COCO', 'RED', 'Le FN'),
    ('BLANC_MANGER_COCO', 'RED', '10 astuces de grand-mère pour tomber enceinte'),
    ('BLANC_MANGER_COCO', 'RED', 'La culpabilité du lendemain'),
    ('BLANC_MANGER_COCO', 'RED', 'Une pastille de Viagra'),
    ('BLANC_MANGER_COCO', 'RED', 'Un concours de T-shirts mouillés'),
    ('BLANC_MANGER_COCO', 'RED', 'La vague Bleu Marine'),
    ('BLANC_MANGER_COCO', 'RED', 'Faire la queue chez Burger King'),
    ('BLANC_MANGER_COCO', 'RED', 'Le minimum syndical'),
    ('BLANC_MANGER_COCO', 'RED', 'La gauche caviar'),
    ('BLANC_MANGER_COCO', 'RED', 'Voter utile'),
    ('BLANC_MANGER_COCO', 'RED', 'Un rhube'),
    ('BLANC_MANGER_COCO', 'RED', 'Mettre de la moquette au mur'),
    ('BLANC_MANGER_COCO', 'RED', 'La certification ISO 9001'),
    ('BLANC_MANGER_COCO', 'RED', 'Les cotisations URSSAF et la CGS'),
    ('BLANC_MANGER_COCO', 'RED', 'Les boulettes de viande Ikea'),
    ('BLANC_MANGER_COCO', 'RED', 'Un crédit conso'),
    ('BLANC_MANGER_COCO', 'RED', 'Réformer en France'),
    ('BLANC_MANGER_COCO', 'RED', 'La sodomie pour les Nuls'),
    ('BLANC_MANGER_COCO', 'RED', 'Un plan à trois'),
    ('BLANC_MANGER_COCO', 'RED', 'Une bonne vieille branlette'),
    ('BLANC_MANGER_COCO', 'RED', 'Être une bête de sexe'),
    ('BLANC_MANGER_COCO', 'RED', 'La première bière du vendredi soir'),
    ('BLANC_MANGER_COCO', 'RED', '72 vierges, comme promis'),
    ('BLANC_MANGER_COCO', 'RED', 'Le cassoulet William Saurin'),
    ('BLANC_MANGER_COCO', 'RED', 'Des chaussettes Mickey'),
    ('BLANC_MANGER_COCO', 'RED', 'Un CAP coiffure'),
    ('BLANC_MANGER_COCO', 'RED', 'Les machettes au Rwanda'),
    ('BLANC_MANGER_COCO', 'RED', 'Une perfusion de sang contaminé'),
    ('BLANC_MANGER_COCO', 'RED', 'Le plombier polonais'),
    ('BLANC_MANGER_COCO', 'RED', 'Boire des bières et fumer des clopes'),
    ('BLANC_MANGER_COCO', 'RED', 'La langue de bois'),
    ('BLANC_MANGER_COCO', 'RED', 'Éviter de manger trop gras, trop salé, trop sucré'),
    ('BLANC_MANGER_COCO', 'RED', 'Le droit de chacun à posséder une Rolex'),
    ('BLANC_MANGER_COCO', 'RED', 'La queue chez Pôle Emploi'),
    ('BLANC_MANGER_COCO', 'RED', 'Le remix techno de la BO de Pirates des Caraïbes'),
    ('BLANC_MANGER_COCO', 'RED', 'Ce je-ne-sais-quoi des Ch\'tis'),
    ('BLANC_MANGER_COCO', 'RED', 'La mise en place d\'une organisation tayloriste'),
    ('BLANC_MANGER_COCO', 'RED', 'Les lourdeurs administratives'),
    ('BLANC_MANGER_COCO', 'RED', 'Mettre le feu à une garderie'),
    ('BLANC_MANGER_COCO', 'RED', 'Sniper la dernière famille de pandas sur Terre'),
    ('BLANC_MANGER_COCO', 'RED', 'Larguer par texto'),
    ('BLANC_MANGER_COCO', 'RED', 'Une promotion canapé'),
    ('BLANC_MANGER_COCO', 'RED', 'Être en galère de PQ'),
    ('BLANC_MANGER_COCO', 'RED', 'Le cannabis thérapeutique'),
    ('BLANC_MANGER_COCO', 'RED', 'La Macarena'),
    ('BLANC_MANGER_COCO', 'RED', 'Youporn comme page d\'acceuil'),
    ('BLANC_MANGER_COCO', 'RED', 'La Gay Pride'),
    ('BLANC_MANGER_COCO', 'RED', 'Un pitbull dans un jardin d\'enfant'),
    ('BLANC_MANGER_COCO', 'RED', 'Le chantage sexuel'),
    ('BLANC_MANGER_COCO', 'RED', 'Un pantalon coupé "poutre-apparente"'),
    ('BLANC_MANGER_COCO', 'RED', 'Les fausses résolutions du 31 Décembre'),
    ('BLANC_MANGER_COCO', 'RED', 'Le savoir-être marseillais'),
    ('BLANC_MANGER_COCO', 'RED', 'La perte des eaux'),
    ('BLANC_MANGER_COCO', 'RED', 'Les petites lèvres'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'immunité parlementaire'),
    ('BLANC_MANGER_COCO', 'RED', 'Jouer au triangle dans un orchestre'),
    ('BLANC_MANGER_COCO', 'RED', 'Pinailler sur le nombre de victimes de la Shoah'),
    ('BLANC_MANGER_COCO', 'RED', 'La discrimination positive'),
    ('BLANC_MANGER_COCO', 'RED', 'Mes poignées d\'amour'),
    ('BLANC_MANGER_COCO', 'RED', 'Rester sous la couette'),
    ('BLANC_MANGER_COCO', 'RED', 'Un bout de salade coincé entre les dents'),
    ('BLANC_MANGER_COCO', 'RED', 'Aller aux prud\'hommes'),
    ('BLANC_MANGER_COCO', 'RED', 'Monseigneur André Vingt-Trois'),
    ('BLANC_MANGER_COCO', 'RED', 'La démobilisation des électeurs'),
    ('BLANC_MANGER_COCO', 'RED', 'La mentalité parisienne'),
    ('BLANC_MANGER_COCO', 'RED', 'Ma Benz\' volume max'),
    ('BLANC_MANGER_COCO', 'RED', 'La tante à Robert'),
    ('BLANC_MANGER_COCO', 'RED', 'Le gras du bide'),
    ('BLANC_MANGER_COCO', 'RED', 'Paumer son alliance en teuf'),
    ('BLANC_MANGER_COCO', 'RED', 'Le botox'),
    ('BLANC_MANGER_COCO', 'RED', 'Le point G'),
    ('BLANC_MANGER_COCO', 'RED', 'Le connard qui ne récure jamais les chiottes'),
    ('BLANC_MANGER_COCO', 'RED', 'Acheter une perruque'),
    ('BLANC_MANGER_COCO', 'RED', 'Amputer les mendiants pour qu\'ils rapportent plus'),
    ('BLANC_MANGER_COCO', 'RED', 'Les roms'),
    ('BLANC_MANGER_COCO', 'RED', 'Les années 80'),
    ('BLANC_MANGER_COCO', 'RED', 'La franche camaraderie des tranchées'),
    ('BLANC_MANGER_COCO', 'RED', 'Bond, James Bond'),
    ('BLANC_MANGER_COCO', 'RED', 'Allumer le feu'),
    ('BLANC_MANGER_COCO', 'RED', 'Un pyjama rayé avec une étoile jaune'),
    ('BLANC_MANGER_COCO', 'RED', 'Un cercueil en kit'),
    ('BLANC_MANGER_COCO', 'RED', 'Une gourmette en argent'),
    ('BLANC_MANGER_COCO', 'RED', 'Des fleurs sur la tombe de Pétain'),
    ('BLANC_MANGER_COCO', 'RED', 'La morosité ambiante'),
    ('BLANC_MANGER_COCO', 'RED', 'Manger 5 fruits et légumes par jour'),
    ('BLANC_MANGER_COCO', 'RED', 'Embrasser la plus belle fille du lycée'),
    ('BLANC_MANGER_COCO', 'RED', 'Un lieu pour se recueillir'),
    ('BLANC_MANGER_COCO', 'RED', 'Mes vacances à St Barth\''),
    ('BLANC_MANGER_COCO', 'RED', 'Aller voir chez les Grecs si j\'y suis'),
    ('BLANC_MANGER_COCO', 'RED', 'Le troussage de domestique'),
    ('BLANC_MANGER_COCO', 'RED', 'Un test de grossesse'),
    ('BLANC_MANGER_COCO', 'RED', 'Une fille qui fait plus que ses 15 ans'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'historique des mes 1 000 dernières navigations Internet, le vrai'),
    ('BLANC_MANGER_COCO', 'RED', 'Tendre la joue gauche'),
    ('BLANC_MANGER_COCO', 'RED', 'Offrir une 8.6 à un SDF'),
    ('BLANC_MANGER_COCO', 'RED', 'Faire un trou dans sa poche pour se masturber en public'),
    ('BLANC_MANGER_COCO', 'RED', 'Vouloir le meilleur pour son chien'),
    ('BLANC_MANGER_COCO', 'RED', 'La traite des noirs'),
    ('BLANC_MANGER_COCO', 'RED', 'Un cancer de la prostate'),
    ('BLANC_MANGER_COCO', 'RED', 'Le traffic d\'organes'),
    ('BLANC_MANGER_COCO', 'RED', 'Le racisme anti-blanc'),
    ('BLANC_MANGER_COCO', 'RED', 'Fort Boyard'),
    ('BLANC_MANGER_COCO', 'RED', 'Échanger des banalités'),
    ('BLANC_MANGER_COCO', 'RED', 'Une fausse couche'),
    ('BLANC_MANGER_COCO', 'RED', 'Un costume 3 pièces Kiabi'),
    ('BLANC_MANGER_COCO', 'RED', 'Les promesses électorales'),
    ('BLANC_MANGER_COCO', 'RED', 'Les habitants d\'Évreux'),
    ('BLANC_MANGER_COCO', 'RED', 'Le passage de la cocaïne au crack'),
    ('BLANC_MANGER_COCO', 'RED', 'La République Démocratique du Congo'),
    ('BLANC_MANGER_COCO', 'RED', 'Le coït'),
    ('BLANC_MANGER_COCO', 'RED', 'Le quenelle'),
    ('BLANC_MANGER_COCO', 'RED', 'Un sextoy pour chien'),
    ('BLANC_MANGER_COCO', 'RED', 'Débrancher Mamie'),
    ('BLANC_MANGER_COCO', 'RED', 'Francky Vincent'),
    ('BLANC_MANGER_COCO', 'RED', 'Un doigt dans le cul'),
    ('BLANC_MANGER_COCO', 'RED', 'La ménopause'),
    ('BLANC_MANGER_COCO', 'RED', 'Le gaz moutarde'),
    ('BLANC_MANGER_COCO', 'RED', 'Les bienfaits de la colonisation'),
    ('BLANC_MANGER_COCO', 'RED', 'La collaboration'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'Algérie frnaçaise'),
    ('BLANC_MANGER_COCO', 'RED', 'Un cintre à défaut de pilule abortive'),
    ('BLANC_MANGER_COCO', 'RED', 'Tenir la chandelle'),
    ('BLANC_MANGER_COCO', 'RED', 'Un 18 trous'),
    ('BLANC_MANGER_COCO', 'RED', 'Aller aux putes'),
    ('BLANC_MANGER_COCO', 'RED', 'Un Samedi soir devant Le plus grand cabaret du monde'),
    ('BLANC_MANGER_COCO', 'RED', 'Les "thaïlandaises"'),
    ('BLANC_MANGER_COCO', 'RED', 'Une crise hémorroïdaire'),
    ('BLANC_MANGER_COCO', 'RED', 'Vomir des spaghetti'),
    ('BLANC_MANGER_COCO', 'RED', 'Le string qui dépasse'),
    ('BLANC_MANGER_COCO', 'RED', 'La famille et les amis'),
    ('BLANC_MANGER_COCO', 'RED', 'La monogamie'),
    ('BLANC_MANGER_COCO', 'RED', 'Se taper la nounou'),
    ('BLANC_MANGER_COCO', 'RED', 'Être puceau à 40 ans'),
    ('BLANC_MANGER_COCO', 'RED', 'Un diabolo grenadine'),
    ('BLANC_MANGER_COCO', 'RED', 'La roulette russe'),
    ('BLANC_MANGER_COCO', 'RED', '7 ans sans sexe'),
    ('BLANC_MANGER_COCO', 'RED', 'Une poire à lavement'),
    ('BLANC_MANGER_COCO', 'RED', 'Un poster Playboy au dessus de mon lit'),
    ('BLANC_MANGER_COCO', 'RED', 'Les populations métissées'),
    ('BLANC_MANGER_COCO', 'RED', 'Un gros paquet'),
    ('BLANC_MANGER_COCO', 'RED', 'La Renault Espace'),
    ('BLANC_MANGER_COCO', 'RED', 'Maubeuge'),
    ('BLANC_MANGER_COCO', 'RED', 'Un déni de grossesse'),
    ('BLANC_MANGER_COCO', 'RED', 'Une faciale'),
    ('BLANC_MANGER_COCO', 'RED', 'Changer de femme pour monter en gamme'),
    ('BLANC_MANGER_COCO', 'RED', 'Une pipe au miel'),
    ('BLANC_MANGER_COCO', 'RED', 'Une AK-47'),
    ('BLANC_MANGER_COCO', 'RED', 'Le Zyklon B'),
    ('BLANC_MANGER_COCO', 'RED', 'La sélection naturelle des espèces'),
    ('BLANC_MANGER_COCO', 'RED', 'Pardonner à moitié'),
    ('BLANC_MANGER_COCO', 'RED', 'Un plan-cul fiable'),
    ('BLANC_MANGER_COCO', 'RED', 'Le concours national du lancer de nain'),
    ('BLANC_MANGER_COCO', 'RED', 'Aller promener le chien'),
    ('BLANC_MANGER_COCO', 'RED', 'Une thérapie de couple'),
    ('BLANC_MANGER_COCO', 'RED', 'Christine Boutin'),
    ('BLANC_MANGER_COCO', 'RED', 'Un boxer porté 8 jours de suite'),
    ('BLANC_MANGER_COCO', 'RED', 'Une blague reciste qui tombe au mauvais moment'),
    ('BLANC_MANGER_COCO', 'RED', 'Jouer au docteur'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'extrême onction'),
    ('BLANC_MANGER_COCO', 'RED', 'Faire croire qu\'on est gay pour pouvoir toucher'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'autotouchage'),
    ('BLANC_MANGER_COCO', 'RED', 'Rater l\'apéro'),
    ('BLANC_MANGER_COCO', 'RED', 'La France d\'en bas'),
    ('BLANC_MANGER_COCO', 'RED', 'La purée blanche sous le prépuce'),
    ('BLANC_MANGER_COCO', 'RED', 'Un Tampax imbibé de Vodka'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'odeur de la clope froide'),
    ('BLANC_MANGER_COCO', 'RED', 'Un chiotte à la turque et rien pour s\'essuyer'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'envie de pisser'),
    ('BLANC_MANGER_COCO', 'RED', 'Zlatan'),
    ('BLANC_MANGER_COCO', 'RED', 'Les pédés'),
    ('BLANC_MANGER_COCO', 'RED', 'Ebola'),
    ('BLANC_MANGER_COCO', 'RED', 'Avoir une mi-molle'),
    ('BLANC_MANGER_COCO', 'RED', 'Se faire gauler en matant un porno'),
    ('BLANC_MANGER_COCO', 'RED', 'Blanc-Manger Coco'),
    ('BLANC_MANGER_COCO', 'RED', 'Tirer la langue avant d\'avaler'),
    ('BLANC_MANGER_COCO', 'RED', 'Une erreur de diagnostic au centre anti-VIH'),
    ('BLANC_MANGER_COCO', 'RED', 'Les alcooliques dépressifs atteints de paralysie faciale'),
    ('BLANC_MANGER_COCO', 'RED', 'Le beurre et l\'argent du beurre'),
    ('BLANC_MANGER_COCO', 'RED', 'L\'abstinence'),
    ('BLANC_MANGER_COCO', 'RED', 'La mauvaise foi'),
    ('BLANC_MANGER_COCO', 'RED', 'Yabon Banania'),
    ('BLANC_MANGER_COCO', 'RED', 'Un Doliprane'),
    ('BLANC_MANGER_COCO', 'RED', 'Al Qaïda'),
    ('BLANC_MANGER_COCO', 'RED', 'Le syndrome de Stockholm');
